root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/lattice ./cmd/lattice"
  bin = "./tmp/lattice"
  include_ext = ["go"]
  exclude_dir = ["tmp", "bin", "frontend", "node_modules", "migrations", "specs", ".git"]
  delay = 1000

[misc]
  clean_on_exit = true
